#---------------------------------#
#      general configuration      #
#---------------------------------#

version: 0.9.{build}

branches:
  except:
    - gh-pages

# Maximum number of concurrent jobs for the project
max_jobs: 1

#---------------------------------#
#    environment configuration    #
#---------------------------------#

clone_folder: c:\projects\RacingToHell

#---------------------------------#
#       build configuration       #
#---------------------------------#

# build platform, i.e. x86, x64, Any CPU. This setting is optional.
platform: Any CPU

# build Configuration, i.e. Debug, Release, etc.
configuration: Debug

# to run your custom scripts instead of automatic MSBuild
build_script:
  #  Fetch mingw64
  - ps: $uri = 'https://github.com/mstorsjo/llvm-mingw/releases/download/20211002/llvm-mingw-20211002-msvcrt-x86_64.zip'
  - ps: Invoke-WebRequest -Uri $uri -OutFile mingw.zip -UserAgent [Microsoft.PowerShell.Commands.PSUserAgent]::Chrome
  - 7z x mingw.zip -aoa

  # Create build directory
  - mkdir build
  - cd build

  #  Set up environment
  - set CC=C:/projects/pdf-editor/llvm-mingw-20211002-msvcrt-x86_64/bin/gcc
  - set CXX=C:/projects/pdf-editor/llvm-mingw-20211002-msvcrt-x86_64/bin/g++
  - set CMAKE_C_COMPILER=C:/projects/pdf-editor/llvm-mingw-20211002-msvcrt-x86_64/bin/clang
  - set CMAKE_CXX_COMPILER=C:/projects/pdf-editor/llvm-mingw-20211002-msvcrt-x86_64/bin/clang
  - set OLD_PATH=%PATH%
  - set PATH=C:/projects/pdf-editor/llvm-mingw-20211002-msvcrt-x86_64/bin;"C:/Program Files (x86)/CMake/bin";"C:/Program Files/Git/bin"

  #  Generate build files
  - cmake -G "Ninja" ../

  #  Build
  - cmake .. -G Ninja -D CMAKE_BUILD_TYPE=Release
  - cmake --build .

  # Test
#  - ctest --output-on-failure
#  - cmake --build . --target test_files
#  - cmake --build . --target test_suite_verapdf
#  - cmake --build . --target test_suite_isartor
#  - cmake --build . --target test_suite_bfosupport

  # Package
  - cmake --build . --target package
  - cmake --build . --target package_source

  #  Reset environment for after_build
  - set PATH=%OLD_PATH%
  - cd ..

#---------------------------------#
#       tests configuration       #
#---------------------------------#
test: false

#---------------------------------#
#      artifacts configuration    #
#---------------------------------#
artifacts:
  - path: build/PDF-Editor-1.0.0-win64.exe

#---------------------------------#
#     deployment configuration    #
#---------------------------------#
#deploy:
#  - provider: GitHub
#    artifact: RacingToHellWindows.zip
#    draft: false
#    prerelease: false
#    on:
#      appveyor_repo_tag: true
