name: Build and Install the CGV framework

on: push

jobs:
  build-ubuntu:
    name: "Ubuntu"
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          submodules: recursive
      - uses: seanmiddleditch/gha-setup-ninja@master

      - name: Install llvm repository
        run: wget https://apt.llvm.org/llvm.sh && chmod +x llvm.sh && sudo ./llvm.sh 11

      - name: Install build tools
        run: sudo apt-get update && sudo apt-get install -y cmake clang-tools-11 clang-11-doc libclang-11-dev

#      - name: Install dependencies
#        run: sudo apt install -y libgl1-mesa-dev libglu1-mesa-dev libx11-dev xorg-dev

      - run: mkdir build

      - name: Run CMake
        working-directory: ./build
        run: cmake .. -G Ninja -D CMAKE_C_COMPILER=/usr/bin/clang-11 -D CMAKE_CXX_COMPILER=/usr/bin/clang++-11

      - name: Build and Install
        working-directory: ./build
        run: cmake --build .

      - name: Run Tests
        working-directory: ./build
        run: ctest

  build-windows:
    name: "Windows"
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          submodules: recursive

      - name: Set up environment variables
        run: |
          "C:/Program Files (x86)/Microsoft Visual Studio/2019/Enterprise/VC/Auxiliary/Build/vcvars64.bat"

      - run: mkdir build

      - name: Run CMake
        working-directory: build
        run: cmake ..

      - name: Build and Install
        working-directory: ./build
        run: cmake --build .

      - name: Run Tests
        working-directory: ./build
        run: ctest
