name: Build and Test

on: push

jobs:
  build:
    name: "Build and Test"
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          submodules: recursive

      # TODO Building has to be done inside a docker image, because gtk-4 is only available in Ubuntu 21.04 and later
      - name: Build and Test
        run: docker build .
