name: Ubuntu

on: push

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - run: mkdir build
      - run: docker build . -t build-image

      - name: Build
        run: |
          docker run -v $(pwd):/app build-image cmake .. -G Ninja -D  CMAKE_BUILD_TYPE=Release
          docker run -v $(pwd):/app build-image cmake --build .

      - name: Test
        run: |
          docker run -v $(pwd):/app build-image ctest --output-no-failure
          docker run -v $(pwd):/app build-image cmake --build . --target test_fuzzer
          docker run -v $(pwd):/app build-image cmake --build . --target test_suite_verapdf
          docker run -v $(pwd):/app build-image cmake --build . --target test_suite_isartor
          docker run -v $(pwd):/app build-image cmake --build . --target test_suite_bfosupport

      - name: Package
        run: |
          docker run -v $(pwd):/app build-image cpack -G ZIP

      # TODO prevent double zipping (maybe unpack before archiving?)
      - name: Archive Artifacts
        uses: actions/upload-artifact@v2
        with:
          path: build/pdf-editor-0.0.1-Linux.zip
