name: Build and Test on Ubuntu

on: push

jobs:
  build:
    name: "Build and Test on Ubuntu"
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      # TODO Building has to be done inside a docker image, because gtk-4 is only available in Ubuntu 21.04 and later
      - name: Build and Test
        run: docker build . -t build-image

      - name: Retrieve Build Artifact
        run: |
          id=$(docker create build-image)
          docker cp $id:/app/build/PDF-Editor-1.0.0-Linux.zip PDF-Editor-1.0.0-Linux.zip
          docker rm -v $id

      # TODO prevent double zipping (maybe unpack before archiving?)
      - name: Archive Artifacts
        uses: actions/upload-artifact@v2
        with:
          path: PDF-Editor-0.0.1-Linux.zip
